name: example_continuous_ml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          apt-get update -y && apt-get install virtualenv -y
          # Your ML workflow goes here
          make virtualenv
          build/virtualenv/bin/python train.py

          # Write your CML report
          cat results.txt >> report.md
          cml-send-comment report.md
